### ISSUE TITLE
[Question] How to run a helloworld application in qemu after build by GCC

### ISSUE THREAD

**Issue by Changqing-JING** [volumit/package_940#1]
I have created a helloworld application and build by gcc

`
#include <stdio.h>
int main(){
    
    printf("hello\n");

    return 0;
}
`

`
./tricore_940_linux/bin/tricore-elf-gcc -o hello.bin hello.c
`
The tricore qemu doesn't provide a user mode emulator, how to run the hello.bin with qemu-system-tricore?
Where can I get a bootloader/kernel to load the hello.bin?

**Comment by volumit** [comment]
If you want to go for real silicon, linker files have to be adapted. QEMU and default linker scripts are adapted for hugh code and data memory to allow the proper execution of the gcc testsuite (some of the test are not fitting in a real device).
